version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "7.0-bullseye"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  pgweb:
    image: sosedoff/pgweb:0.11.11
    restart: unless-stopped
    network_mode: service:db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/pic-k?sslmode=disable
    depends_on:
      - db

volumes:
  postgres-data: null